import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const funnelSans = Funnel_Sans({
    subsets: ["latin"],
    variable: "--font-funnel-sans",
});

const clashDisplay = localFont({
    src: [
        {
            path: "./fonts/ClashDisplay-Extralight.otf",
            weight: "200",
            style: "normal",
        },
        {
            path: "./fonts/ClashDisplay-Light.otf",
            weight: "300",
            style: "normal",
        },
        {
            path: "./fonts/ClashDisplay-Regular.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/ClashDisplay-Medium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/ClashDisplay-Semibold.otf",
            weight: "600",
            style: "normal",
        },
        {
            path: "./fonts/ClashDisplay-Bold.otf",
            weight: "700",
            style: "normal",
        },
    ],
    display: "swap",
    variable: "--font-clash-display",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${clashDisplay.variable} ${funnelSans.variable}`}
        >
            <body className="flex min-h-screen flex-col">
                <NavBar />
                <main className="grow">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
